name: deploy

on:
  push:
    branches: ['main']

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - uses: pnpm/action-setup@v2
      - run: pnpm -v

      - run: pnpm install

      - run: pnpm exec tsx ./.vitepress/scripts/updateVersion.ts
      - run: pnpm run docs:build-mirror
      
      - name: Publish package
        run: |
          pnpm config set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
          pnpm publish --no-git-checks

      - run: git checkout .
      - run: curl -X PUT 'https://registry-direct.npmmirror.com/@gkd-kit/docs/sync'

      - uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: gkd-docs
          directory: ./.vitepress/dist
